// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {devices} from '../models';

export function GetAvailableDevices():Promise<Array<devices.Device>>;
