// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {devices} from '../models';
import {tshark} from '../models';

export function GetCapturedPackets(arg1:number,arg2:number):Promise<Array<types.CapturedPacket>>;

export function GetDevices():Promise<Array<devices.Device>>;

export function GetPacketCount():Promise<number>;

export function GetPacketDetails(arg1:number):Promise<tshark.PacketDetails>;

export function Greet(arg1:string):Promise<string>;

export function StartCapture(arg1:string):Promise<void>;
