// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCapturedPackets(arg1, arg2) {
  return window['go']['main']['App']['GetCapturedPackets'](arg1, arg2);
}

export function GetDevices() {
  return window['go']['main']['App']['GetDevices']();
}

export function GetPacketCount() {
  return window['go']['main']['App']['GetPacketCount']();
}

export function GetPacketDetails(arg1) {
  return window['go']['main']['App']['GetPacketDetails'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function StartCapture(arg1) {
  return window['go']['main']['App']['StartCapture'](arg1);
}
