// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {devices} from '../models';

export function GetDevices():Promise<Array<devices.Device>>;

export function Greet(arg1:string):Promise<string>;
