// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {capture} from '../models';
import {devices} from '../models';

export function ClearCapturedPackets():Promise<void>;

export function GetCapturedPackets():Promise<Array<capture.CapturedPacket>>;

export function GetDevices():Promise<Array<devices.Device>>;

export function Greet(arg1:string):Promise<string>;

export function StartCapture(arg1:string):Promise<void>;
